export const policies = [
  {
    id: 'POL-101',
    name: 'Velocity spike containment',
    condition: 'PSI > 0.20 on deviceVelocity for 3 consecutive polls',
    action: 'Force manual review for flagged transactions',
    escalation: 'Fraud Ops Lead',
    lastModified: '2026-08-01T18:10:00Z',
    modifiedBy: 'A. Chen',
    version: '1.4',
  },
  {
    id: 'POL-102',
    name: 'High confidence override control',
    condition: 'Confidence < 0.55 with amount > $2,500',
    action: 'Escalate to compliance within 15 minutes',
    escalation: 'Compliance Queue',
    lastModified: '2026-08-01T13:40:00Z',
    modifiedBy: 'J. Patel',
    version: '2.1',
  },
  {
    id: 'POL-103',
    name: 'Geo distance alerting',
    condition: 'Geo distance > 180 miles and device age < 7 days',
    action: 'Hold transaction pending analyst review',
    escalation: 'Risk Engineer On-call',
    lastModified: '2026-07-31T20:25:00Z',
    modifiedBy: 'M. Rivera',
    version: '1.9',
  },
  {
    id: 'POL-104',
    name: 'Repeat chargeback protection',
    condition: 'Previous chargebacks >= 2 in a 30 day window',
    action: 'Decline automatically and file audit record',
    escalation: 'Compliance Lead',
    lastModified: '2026-07-31T09:15:00Z',
    modifiedBy: 'S. Howard',
    version: '3.0',
  },
  {
    id: 'POL-105',
    name: 'Semantic drift freeze',
    condition: 'Embedding distance > 0.30 and ADWIN severity = High',
    action: 'Freeze model approvals until review completes',
    escalation: 'Model Governance Board',
    lastModified: '2026-08-01T07:55:00Z',
    modifiedBy: 'L. Kim',
    version: '1.2',
  },
]

export const policyHistory = [
  {
    id: 'H-001',
    policyName: 'Velocity spike containment',
    changedAt: '2026-08-01T18:10:00Z',
    changedBy: 'A. Chen',
    changeSummary: 'Raised PSI threshold from 0.18 to 0.20 after false positive review.',
  },
  {
    id: 'H-002',
    policyName: 'High confidence override control',
    changedAt: '2026-08-01T13:40:00Z',
    changedBy: 'J. Patel',
    changeSummary: 'Shortened escalation SLA from 30 minutes to 15 minutes.',
  },
  {
    id: 'H-003',
    policyName: 'Geo distance alerting',
    changedAt: '2026-07-31T20:25:00Z',
    changedBy: 'M. Rivera',
    changeSummary: 'Expanded manual review scope to include device age checks.',
  },
  {
    id: 'H-004',
    policyName: 'Repeat chargeback protection',
    changedAt: '2026-07-31T09:15:00Z',
    changedBy: 'S. Howard',
    changeSummary: 'Converted decline action from advisory to automatic.',
  },
  {
    id: 'H-005',
    policyName: 'Semantic drift freeze',
    changedAt: '2026-08-01T07:55:00Z',
    changedBy: 'L. Kim',
    changeSummary: 'Added ADWIN severity gate before model freeze triggers.',
  },
]