from __future__ import annotations

DEFAULT_MODEL_NAME = "fraud_classifier"
DEFAULT_MODEL_VERSION = "1.0.0"
DEFAULT_RISK_THRESHOLD = 0.75
DEFAULT_REVIEW_THRESHOLD = 0.45
DEFAULT_DRIFT_THRESHOLD = 0.2
EPSILON = 1e-9
